name: CI
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format raw \
              --image-size 200M \
              --script-chroot \
              alpine.img -- ./prepareISO.sh
          curl --upload-file ./alpine.img https://transfer.sh